### ISSUE TITLE
On Windows > NULL creates file

### ISSUE THREAD

**Issue by CedNet** [Indatus/dispatcher#118]
Hi again, on my Windows machine with version 1.4 the --debug says the following is run:

    command:send_reminders: START /B php G:\xxx/artisan command:send_reminders > NULL

The problem is that on Windows this creates a file called NULL in the application root. I believe this is not intended and hopefully can be resolved. Can't see anywhere in the docs how to prevent it.

Could you please somehow allow for the option of excluding the last argument after the command is run? Or, simply if Windows, no > NULL is appended.

**Comment by bkuhl** [comment]
Thanks @cantecim
