### ISSUE TITLE
different timings for different options of a command

### ISSUE THREAD

**Issue by nhp** [Indatus/dispatcher#120]
Right now i use something like 
```php
public function schedule(Schedulable $scheduler)
{
  return $scheduler->opts(['target' => 'local'])->daily()->hours('*')->minutes('*/15');
}
```
is it possible to have different timings for different values of `target`? Or do i have to use a different command for it to work ?  I also tried to use `opts(['target' => ['local','local2'])` for runs on 2 different targets, but it is only running for `local2` in this case.

**Comment by bkuhl** [comment]
You can do this:

```php
public function schedule(Schedulable $scheduler)
{
  return [
        $scheduler->opts(['target' => 'local'])->daily()->hours('*')->minutes('*/15'),
        $scheduler->opts(['target' => 'local2'])->daily()->hours('*')->minutes('*/15')
  ];
}
```
