### ISSUE TITLE
Deploy on Windows.

### ISSUE THREAD

**Issue by PabloZagni** [Indatus/dispatcher#124]
Dispacher is working perfectly in my development environment with Vagrant / Homestead VM.
When I deploy to my Windows XP production server I open a console and type:

php artisan scheduled:run 

and get the error:

Invalid argument /usr

How can I solve this? 
Thanks!

**Comment by bkuhl** [comment]
I'm not sure how you could be seeing that.  `/usr` is not used as an argument anywhere that I can think of.  Try adding the `--debug` option to the command and post hte output.

https://github.com/Indatus/dispatcher/blob/1.4/src/Indatus/Dispatcher/Services/CommandService.php#L182 is the only place that is used and it's only used on linux.

**Comment by PabloZagni** [comment]
Runing: php artisan sheduled:run --debug

Error:
The "--debug" option does not exists.

**Comment by bkuhl** [comment]
What version are you using?  In the latest release that option exists: https://github.com/Indatus/dispatcher/blob/1.4/src/Indatus/Dispatcher/Commands/Run.php#L56

**Comment by PabloZagni** [comment]
Solved! I was Using version 1.2 as showed on video tutor... Sorry for my mistake.
Thank you VERY MUCH for your time.
Greeting from Argentina.
