### ISSUE TITLE
--env does not get passed into the scheduled commands

### ISSUE THREAD

**Issue by rtconner** [Indatus/dispatcher#125]
If I run `./artisan scheduled:run --env=production` the env parameter does not get passed along into the scheduled commands themselves

**Comment by maximebeaudoin** [comment]
See #64, #85, #101

**Comment by rtconner** [comment]
I'll look into as soon as I can't. Not sure why I would be having this issue if you already have fixed it.

**Comment by rtconner** [comment]
Looks like only #64 is in the latest stable branch of 1.4.1. And there was no documentation to follow.
Anyways, I was able to pass along the environment by with $scheduler->opts(['env'=>'blah'])

So this code passed the environment into the individual command ..

```php
public function schedule(Schedulable $scheduler)
	{
        return $scheduler
			->opts(['env'=>\App::environment()])
			->everyWeekday()
			->hours(16);
	}
}
```
