### ISSUE TITLE
Ask : i wanna use schedule for run php codes

### ISSUE THREAD

**Issue by h-rafiee** [Indatus/dispatcher#126]
Hey; thanks for this liberary for make easy work with cron.
but i can't figure out where i should write my command.
or maybe this is my wrong ...
i wanna daily expire to update my Database
i wrote artisan schadule:run and it's run. after i get summary but its empty ...
see that ...
![cron](https://cloud.githubusercontent.com/assets/1610989/6346419/13b20400-bc25-11e4-8e9e-3c6585c5cd77.png)

and this my codes
![codes](https://cloud.githubusercontent.com/assets/1610989/6346428/2854e29c-bc25-11e4-85b8-549ce1450e05.png)

**Comment by bkuhl** [comment]
Your question isn't specific to Dispatcher, but more of a general "how do I add functionality to an artisan command".  It'd probably be helpful for you to check out Laracasts.com for a tutorial.  https://laracasts.com/lessons/laracasts-crons-and-notifications might be useful
