### ISSUE TITLE
Doesn't propagate --env flag

### ISSUE THREAD

**Issue by collegeman** [Indatus/dispatcher#127]
My `App::detectEnvironment` defaults to `local`. I can run `php artisan schedule:run --env=production`, but Dispatcher doesn't propagate the `env` flag to the commands that are scheduled to run. I think the solution is just to add `--env=$environment` where `$environment` is set to `App::environment()` to the `$commandPieces` array before line 202 in `CommandService`.

**Comment by collegeman** [comment]
Oh weird, I just discovered this fix is already in master. Why do I not have the latest via composer?

**Comment by collegeman** [comment]
Can you guys please release 1.4.2 up to this commit: https://github.com/Indatus/dispatcher/commit/fdd23d75e4cfbd9ccddd724c742773b4edc4c2e5

**Comment by collegeman** [comment]
I just need that Environment fix to be available to my Laravel 4 application.

**Comment by bkuhl** [comment]
Done: https://github.com/Indatus/dispatcher/releases/tag/v1.4.2

The master branch was working towards a Laravel 5 implementation which has since been discontinued so this is based off of the 1.4 branch.

**Comment by collegeman** [comment]
Bad ass!
