### ISSUE TITLE
removing command file causes scheduled:summary to crash

### ISSUE THREAD

**Issue by rickghome** [Indatus/dispatcher#132]
When I run scheduled:summary from cron on Yosemite, it works. When I run scheduled:run, I get a php env error. Mcrypt is present, and no other errors are present. Any debug tips?

**Comment by rickghome** [comment]
ok -- I presume that you just remove the command registration.

**Comment by rickghome** [comment]
When I run scheduled:summary from cron, it works. When I run scheduled:run, I get a php env error. Mcrypt is present, and no other errors are present.

**Comment by bkuhl** [comment]
Can you show me the exact output you're seeing?
