### ISSUE TITLE
What sort of dependencies for Laravel does this project have?

### ISSUE THREAD

**Issue by OptimusCrime** [Indatus/dispatcher#133]
Not so much an issue as a question. 

Sorry for asking this but I found dispatcher and it looks very cool and I would like to use it in my project. However, I am not using Laravel in my project. What dependencies does dispatcher have towards Laravel? Does it just use some of the functionality or does it require the project to be an actual Laravel app?

**Comment by bkuhl** [comment]
It's completely dependent on Laravel, so if you're not using Laravel then you can't utilize this package.

**Comment by OptimusCrime** [comment]
Ah, damnit. Well, thanks for responding quickly :)
