### ISSUE TITLE
Question: Laravel 5.x schedule:summary

### ISSUE THREAD

**Issue by yajra** [Indatus/dispatcher#134]
Is there a counterpart command for `scheduled:summary` on Laravel 5? Docs only provides `schedule:run`.

**Comment by bkuhl** [comment]
I don't believe there is.  I'm not sure it's even possible for Laravel 5 to
do that since you can schedule such a wide variety of things including
closures.

**Comment by yajra** [comment]
it's sad to know that it's not available on Laravel 5. It was a good and very useful command. It assures you that your command is properly scheduled. I already made a request on laravel framework for this. Hopefully someone can implement it. Thanks!
