### ISSUE TITLE
Every Hours not running properly

### ISSUE THREAD

**Issue by ideadx** [Indatus/dispatcher#135]
I have 
public function schedule(Schedulable $scheduler)
	{
		return $scheduler->everyHours(4);
	}
and this is how summary looks like
| *              | doh:eat           |           | *      | */4    | *            | *     | *           |        |

If you want to run cron every 4 hour, shouldn't it be 
| *              | doh:eat           |           | 0      | */4    | *            | *     | *           |        |

because this ScheduledCommand currently firing every few mins.

version 1.* with laravel 4.2
Thanks.

**Comment by bkuhl** [comment]
This is the expected functionality of this feature.  `everyHours()` does not adjust the minutes so that you maintain flexibility to do things like... to accomplish the desired scheduling, you'll need to do `$scheduler->minutes(0)->everyHours(4)`.
