### ISSUE TITLE
[Feature] pcntl_fork in leui of exec

### ISSUE THREAD

**Issue by wjaspers** [Indatus/dispatcher#138]
`exec` is easy, unfortunately, no one's watching. 
With `pcntl_fork` we can watch for zombies and kill them before they take over!

I'm still gathering data on the issue, however, have encountered Schedulable commands which didn't terminate as expected. The executed process hangs indefinitely until someone identifies and kills its pid.

It would be nice if a command could provide a maximum run time.

**Comment by bkuhl** [comment]
Since Laravel 5 includes it's own scheduling Dispatcher has been discontinued.  If you submit a PR with this functionality I'd gladly include it if you can confirm that it works and ensure test coverage.
