### ISSUE TITLE
 Call to undefined method [package] 

### ISSUE THREAD

**Issue by akasham67** [Indatus/dispatcher#139]
I already Install ~2.0@dev version in my Laravel 5 project. But when I added Add this line 'Indatus\Dispatcher\ServiceProvider' to the providers array in my config/app.php file and run php artisan then it showed me this error """ [BadMethodCallException] Call to undefined method [package] "" 

Please give me a solution. 

Thank you.

**Comment by bkuhl** [comment]
The scheduling concept is now baked directly into Laravel 5 so you no longer need Dispatcher.  Checkout http://laravel.com/docs/5.1/scheduling

This package has been discontinued.
