### ISSUE TITLE
Class 'Orchestra\Testbench\TestCase' not found

### ISSUE THREAD

**Issue by bpfruin** [Indatus/dispatcher#141]
I'm a novice developer. I get the following error when I try to run PHPUnit on my project:

PHP Fatal error:  Class 'Orchestra\Testbench\TestCase' not found in .../laravel/vendor/indatus/dispatcher/tests/TestCase.php

I'm not sure why it would look here for that file but I did not develop this app and the people that did are not reachable. 

My TestCase.php file DOES extend Orchestra/Testbench/TestCase so I have no idea why this error is being thrown.  Sorry if this isn't the appropriate forum for this issue.  Thanks in advance.

**Comment by GrahamCampbell** [comment]
Sorry, I don't see how this is a bug with this package? You probably just forgot to install orchestra/testbench.

**Comment by GrahamCampbell** [comment]
> PHP Fatal error: Class 'Orchestra\Testbench\TestCase' not found in .../laravel/vendor/indatus/dispatcher/tests/TestCase.php

Why are you trying to run those tests?

**Comment by bpfruin** [comment]
orchestra/testbench is definitely installed.  I'm just trying to set up unit testing in my app and when I run "phpunit" I get the aforementioned error.

**Comment by bkuhl** [comment]
From which directory are you running tests?  It sounds like you might be trying to run Dispatcher's tests rather or in addition to your application's tests.

**Comment by bpfruin** [comment]
vendor/bin/phpunit

**Comment by GrahamCampbell** [comment]
@bpfruin That's not not the question that was asked. Run `pwd` please. ;)

**Comment by bpfruin** [comment]
Ah I see... I'm running "vendor/bin/phpunit" from my laravel directory.

**Comment by GrahamCampbell** [comment]
Can we see your composer.json please?

**Comment by bpfruin** [comment]
Problem solved.  I was adding orchestra to the wrong composer.json file.  Thank you very very much for being so patient and helpful.

**Comment by GrahamCampbell** [comment]
Please close this. ;)

**Comment by bpfruin** [comment]
Is there anyway to use this library WITHOUT also using orchestra?

**Comment by GrahamCampbell** [comment]
Yes. dev-dependencies are NOT inherited by composer.

**Comment by bpfruin** [comment]
Every time I try to run phpunit, I get the 'Orchestra\Testbench\TestCase' not found... error in ../dispatcher/tests/TestCase.php.

All my tests inherit from Illuminate\Foundation\Testing\TestCase and I've even excluded the indatus directory in my phpunit.php file while specifying the specific test suite I want(Although there is only one in the project).  I've even tried uninstalling and reinstalling this library.  I've tried everything I can think of and read through all the docs I can and I'm still getting this error.

So really I should probably refine my question... Is there any way to use this library WITHOUT also using orchesta while also using phpunit.
