### ISSUE TITLE
ERROR: exception 'InvalidArgumentException' with message 'Command "command:check" is not defined.

### ISSUE THREAD

**Issue by mh-jamil** [Indatus/dispatcher#143]
Hello, 

I am using your code to run a cron job every minute, and I am getting this error on live server (works fine on my local machine). Here is what I have done:

	 <?php

	use Indatus\Dispatcher\Scheduling\ScheduledCommand;
	use Indatus\Dispatcher\Scheduling\Schedulable;
	use Indatus\Dispatcher\Drivers\Cron\Scheduler;
	use Symfony\Component\Console\Input\InputOption;
	use Symfony\Component\Console\Input\InputArgument;

	class TestCommand extends ScheduledCommand {

		/**
		 * The console command name.
		 *
		 * @var string
		 */
		protected $name = 'command:check';

		/**
		 * The console command description.
		 *
		 * @var string
		 */
		protected $description = 'Check if the meberships are verified.';

		/**
		 * Create a new command instance.
		 *
		 * @return void
		 */
		public function __construct()
		{
			parent::__construct();
		}

		/** 
		 * When a command should run
		 *
		 * @param Scheduler $scheduler
		 * @return \Indatus\Dispatcher\Scheduling\Schedulable
		 */
		public function schedule(Schedulable $scheduler)
		{
			return $scheduler->everyMinutes(1);
		}

		/**
		 * Execute the console command.
		 *
		 * @return mixed
		 */
		public function fire()
		{
			Log::info('I was here @ ' . date('H:i:s'));
		}

		/**
		 * Get the console command arguments.
		 *
		 * @return array
		 */
		protected function getArguments()
		{
			return array(
				// array('example', InputArgument::REQUIRED, 'An example argument.'),
			);
		}

		/**
		 * Get the console command options.
		 *
		 * @return array
		 */
		protected function getOptions()
		{
			return array(
				// array('example', null, InputOption::VALUE_OPTIONAL, 'An example option.', null),
			);
		}

	}

So basically, I'm just writing a line in my **Storage/laravel.log** file every time the scheduler is run. When I do `**php artisan scheduled:run**` on my local machine, it writes a new line in my log file.

Now, I've uploaded the code on my server and have created a cron job as:

[http://awesomescreenshot.com/09a64zii1f](http://awesomescreenshot.com/09a64zii1f)

The cron is running every minute as expected and the log file is also being updated every minute, but instead of the message I am writing in log file, its writing following error every minute:

	 [2016-09-24 09:20:01] production.ERROR: exception 'InvalidArgumentException' with message 'Command "command:check" is not defined.

	 Did you mean this?
	     command:make' in /home/mhjamil/public_html/l4-cron/test/vendor/symfony/console/Symfony/Component/Console/Application.php:564
	 Stack trace:
	 #0 /home/mhjamil/public_html/l4-cron/test/vendor/symfony/console/Symfony/Component/Console/Application.php(190): Symfony\Component\Console\Application->find('command:check')
	 #1 /home/mhjamil/public_html/l4-cron/test/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	 #2 /home/mhjamil/public_html/l4-cron/test/artisan(58): Symfony\Component\Console\Application->run()
	 #3 {main} [] []

Can you please help me with this and tell what I am doing wrong, this is just a test project that is why I'm running the cron every minute. I want to use this in a real project in L4.2 (which I did long ago), and want to run scheduler once every day.

Looking forward to your reply soon.

**Comment by mh-jamil** [comment]
Cron command screenshot is attached for you convenience. 

![screenshot](https://cloud.githubusercontent.com/assets/10434700/18807540/a1342002-8252-11e6-9598-de963e66e216.png)

**Comment by mh-jamil** [comment]
And by the way, I've registered the command in **app/start/artisan.php** as 

`Artisan::add(new TestCommand);`

Also the command `php artisan command:check` runs successfully on my local machine, but when I upload it to my server it says **Command "command:check" is not defined**.

**Comment by bkuhl** [comment]
I don't see any obvious errors in the code or setup, however this isn't a Dispatcher issue so I'm going to close it out.  I'd highly suggest posting on StackOverflow.com.
