### ISSUE TITLE
Cannot get Laracast example to fire MAC OSX Mavricks

### ISSUE THREAD

**Issue by jimmck** [Indatus/dispatcher#67]
Hi,

I create the cron command file and start crontab.  But it never fires.  If I enter the command manually, it works.  When do crontab -l it shows the job????
- \* \* \* \* php /Users/jimm/WebProjects/laravel42/artisan scheduled:run 1>> /dev/null 2>&1

**Comment by phuclh** [comment]
@jimmck I has same problem with you. The command works when I run it in terminal. Please help me.

**Comment by bkuhl** [comment]
Which crontab did you add it to?  The root crontab or a specific user's crontab?

**Comment by phuclh** [comment]
I create a cron.txt in my folder project and using `crontab cron.txt` command

**Comment by bkuhl** [comment]
Which user are you running that command as?  Can you also provide the contents of the `cron.txt`?

**Comment by phuclh** [comment]
This is my `cron.txt` file:

`* * * * * php /Users/mac/Code/myproject/artisan scheduled:run 1>> /dev/null 2>&1`

**Comment by jimmck** [comment]
Hi,

I had to put the path in my cron file.  Once done done, all works fine.
MAC OSX, Laravel 4, PHP 5.6.3

Here is my file:

SHELL=/bin/bash
PATH=/Applications/:/Applications/XAMPP/xamppfiles/bin/:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
* * * * * php /Users/jimm/WebProjects/laravel42/artisan scheduled:run 1>>
/dev/null 2>&1


Regards,
Jim

**Comment by bkuhl** [comment]
@phuclh Which crontab did you setup that crontab on?  If it's on the root crontab then that cron command is invalid and will not run.  It's on the root crontab if you added while either....

1) Being logged in as root
2) used `sudo crontab` or some other `sudo` to edit/install the cron

**Comment by phuclh** [comment]
I edit my `cron.txt` file like:
`SHELL=/bin/bash
PATH=/Applications/:/Applications/XAMPP/xamppfiles/bin/:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
* * * * * php /Users/mac/Code/myproject/artisan scheduled:run 1>> /dev/null 2>&1`

And It fired :D.

Thank you very much @jimmck @bkuhl

**Comment by jimmck** [comment]
Cool !!! Enjoy!

Jim
