### ISSUE TITLE
exception 'InvalidArgumentException' with message 'There are no commands defined in the "xxx" namespace.'

### ISSUE THREAD

**Issue by nebestpal** [Indatus/dispatcher#68]
I'm getting this error:

[2014-08-24 20:19:02] staging.ERROR: exception 'InvalidArgumentException' with message 'There are no commands defined in the "trusty" namespace.' in /home/trustywebapp/public_html/stagingtrusty/vendor/symfony/console/Symfony/Component/Console/Application.php:516
Stack trace:
#0 /home/trustywebapp/public_html/stagingtrusty/vendor/symfony/console/Symfony/Component/Console/Application.php(550): Symfony\Component\Console\Application->findNamespace('trusty')
#1 /home/trustywebapp/public_html/stagingtrusty/vendor/symfony/console/Symfony/Component/Console/Application.php(190): Symfony\Component\Console\Application->find('trusty:log')
#2 /home/trustywebapp/public_html/stagingtrusty/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/trustywebapp/public_html/stagingtrusty/artisan(58): Symfony\Component\Console\Application->run()
#4 {main} [] []

This is what I put in the cpanel cron job:
php  /home/trustywebapp/public_html/stagingtrusty/artisan scheduled:run 1>> /dev/null 2>&1

Pls help.

**Comment by Caneco** [comment]
This has been solved?

I'm trying to use Dispacher and I keep getting this error… I've already read all the comments as make all suggestion and still no luck.

**Comment by sparkeleven** [comment]
@Caneco in my /app/config/packages/indatus/dispatcher/config.php I have 

 'executable' => '/usr/bin/php-cli'

Does that help?

**Comment by Caneco** [comment]
@sparkeleven that really made the trick! Thank you!

**Comment by xwlee** [comment]
@sparkeleven Thank, it solved!

**Comment by ideadx** [comment]
if you dont find config files in app/config
rung: php artisan config:publish indatus/dispatcher

**Comment by Caneco** [comment]
On the other day this happened to me with this issue…

![a6pswtfcuai7n-5](https://cloud.githubusercontent.com/assets/502041/8302028/12b39b0e-198b-11e5-86b3-8b95db18b5f9.jpg)
