### ISSUE TITLE
in laravel 4 showing 'Impossible CRON expression'

### ISSUE THREAD

**Issue by hardevine** [Indatus/dispatcher#99]
having same error in log file.
in schedule method it is -

``` php
return $scheduler->daily()->hours(4)->minutes(17);
```

on running following from shell it says 'No schedules were due'
scheduled:run --debug

**Comment by usmanhalalit** [comment]
@bkuhl, I'm having the exact same issue.

Laravel 4.2
"indatus/dispatcher": "1.4.*"
Forge Server with Linode.

Log:

    {"message":"Impossible CRON expression","context":[],"level":400,"level_name":"ERROR","channel":"production","datetime":{"date":"2015-01-22 02:59:01.567212","timezone_type":2,"timezone":"EST"}

Summary:

    +----------------+-----------------------------------+-----------+--------+------+--------------+-------+-------------+------+
    | Environment(s) | Name                              | Args/Opts | Minute | Hour | Day of Month | Month | Day of Week | Run as |
    +----------------+-----------------------------------+-----------+--------+------+--------------+-------+-------------+------+
    | *              | cron:update_campaign_clicks_count |           | 0      | 0    | *            | *     | *           |        |
    +----------------+-----------------------------------+-----------+--------+------+--------------+-------+-------------+--------+

Cron:

    /usr/bin/php /home/forge/domain.com/artisan scheduled:run 1>> /dev/null 2>&1


Any help without hacking the package would be highly appreciated.
